### ISSUE TITLE
Can this used server side swift

### ISSUE THREAD

**Issue by nonfungibletunji** [david-swift/GraphQLKit-macOS#1]
### Describe the solution you'd like

I would like to use with vapor

### Describe alternatives you've considered

N/a

### Additional context

N/a

**Comment by david-swift** [comment]
Thanks for opening the issue, @nonfungibletunji 

This package works with the first Betas of Swift 5.9 at the moment. At some point, the new Swift macros got an update that broke this package. I'll fix it tomorrow!

**Comment by david-swift** [comment]
Okay, as there currently aren't helpful error messages when the tests fail and I'm working on something else, I'll wait with fixing it until the stable release of Swift 5.9. Sorry!
